import { Metadata } from "next";


export const metadata: Metadata = {
  title: "FAQ",
  description: "Generated by Next.js",
};

export default function FaqLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      
      {children}
      
    </>
  );
}
